# Generated by Django 5.1.7 on 2025-03-17 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_restoran', models.CharField(max_length=255)),
                ('gambar_restoran', models.ImageField(blank=True, null=True, upload_to='restoran_images/')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restoran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_menu', models.CharField(max_length=255)),
                ('foto_makanan', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('harga_makanan', models.IntegerField()),
                ('keterangan_makanan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restoran.restoran')),
            ],
        ),
    ]
